all:
	gcc BresenhamLine.c -L./Linux -lglfw3 -ldl -lm -lX11 -lglad -lGL -lGLU -lpthread -O3 -o BresenhamLine.o
val:
	gcc BresenhamLine.c -L./Linux -lglfw3 -ldl -lm -lX11 -lglad -lGL -lGLU -lpthread -O3 -g -Wall -o BresenhamLine.o
clean:
	rm BresenhamLine.o