all:
	gcc VanDeGraaphGenerator.c -L./Linux -lglfw3 -ldl -lm -lX11 -lglad -lGL -lGLU -lpthread -O3 -o VanDeGraaphGenerator.o
val:
	gcc VanDeGraaphGenerator.c -L./Linux -lglfw3 -ldl -lm -lX11 -lglad -lGL -lGLU -lpthread -O3 -g -Wall -o VanDeGraaphGenerator.o
clean:
	rm VanDeGraaphGenerator.o