all:
	gcc Heapsort.c -L./Linux -lglfw3 -ldl -lm -lX11 -lglad -lGL -lGLU -lpthread -O3 -o Heapsort.o
val:
	gcc Heapsort.c -L./Linux -lglfw3 -ldl -lm -lX11 -lglad -lGL -lGLU -lpthread -O3 -g -Wall -o Heapsort.o
clean:
	rm Heapsort.o