all:
	gcc Wagner-Fischer.c -L./Linux -lglfw3 -ldl -lm -lX11 -lglad -lGL -lGLU -lpthread -O3 -o Wagner-Fischer.o
val:
	gcc Wagner-Fischer.c -L./Linux -lglfw3 -ldl -lm -lX11 -lglad -lGL -lGLU -lpthread -O3 -g -Wall -o Wagner-Fischer.o
clean:
	rm Wagner-Fischer.o